name: workflow

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_products:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout scraped-data branch
#        uses: actions/checkout@v3
#        with:
#          ref: scraped-data
#          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create data directory
        run: |
          mkdir -p data

      - name: Run webscraper
        timeout-minutes: 10
        env:
          PYTHONUNBUFFERED: 1
        run: python webscraping/main.py

#      - name: Commit and push CSV
#        run: |
#          git config user.name "github-actions[bot]"
#          git config user.email "github-actions[bot]@users.noreply.github.com"
#          git add data/products.csv
#          git commit -m "Update CSV (automated)" || echo "No changes to commit"
#          git push

#      - name: Create or update release and upload CSV
#        env:
#          GITHUB_TOKEN: ${{ secrets.REPO_RELEASE_TOKEN }}
#        run: |
#          RELEASE_TAG="latest-csv"
#          RELEASE_NAME="Automated CSV Release"
#
#          gh release view $RELEASE_TAG || gh release create $RELEASE_TAG --title "$RELEASE_NAME" --notes "Latest CSV data"
#          gh release upload $RELEASE_TAG data/products.csv --clobber

      - name: Upload CSV to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          python webscraping/upload_to_gdrive.py data/products.csv 1VX8IXy8QIjf0WI92R_k-ws7RMEtkmhW5