name: workflow

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_products:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download spaCy model
        run: python -m spacy download en_core_web_lg

      - name: Remove old CSV
        run: rm -f data/products.csv

      - name: Run webscraper
        timeout-minutes: 15
        env:
          PYTHONUNBUFFERED: 1
          FARM2FLORIST_LOGIN_EMAIL: ${{ secrets.FARM2FLORIST_LOGIN_EMAIL }}
          FARM2FLORIST_LOGIN_PASSWORD_HASHED: ${{ secrets.FARM2FLORIST_LOGIN_PASSWORD_HASHED }}
          FARM2FLORIST_LOGIN_RANDOM_KEY: ${{ secrets.FARM2FLORIST_LOGIN_RANDOM_KEY }}
        run: python webscraping/main.py

      - name: Create or update release and upload CSV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG="latest-csv"
          RELEASE_NAME="Automated CSV Release"

          gh release view $RELEASE_TAG || gh release create $RELEASE_TAG --title "$RELEASE_NAME" --notes "Latest CSV data"
          gh release upload $RELEASE_TAG data/products.csv --clobber